const base = { a: 1, b: 2 };
const over = { ...base, b: 3, c: 4 };
if (JSON.stringify(over) !== '{"a":1,"b":3,"c":4}') throw new Error(JSON.stringify(over));
const merged = { ...{ x: 1 }, ...{ y: 2 } };
if (merged.x !== 1 || merged.y !== 2) throw new Error('merge');
const src = { a: 1, get b() { return this.a + 1 } };
Object.defineProperty(src, 'hidden', { value: 9, enumerable: false });
const copy = { ...src };
if (copy.b !== 2) throw new Error('getter not invoked at copy time: ' + copy.b);
if ('hidden' in copy) throw new Error('non-enumerable copied');
const { a, ...rest } = src;
if (rest.b !== 2 || 'hidden' in rest || 'a' in rest) throw new Error(JSON.stringify(rest));
if (JSON.stringify({ ...null, ...'ab' }) !== '{"0":"a","1":"b"}') throw new Error('primitive spread');
